// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe6tZshvP22qM3Zvbo6iZH33pZKRMI0SI',
    appId: '1:732608529588:android:b0b230c57378e82f6a43e1',
    messagingSenderId: '732608529588',
    projectId: 'push-notification-b9a18',
    databaseURL: 'https://push-notification-b9a18-default-rtdb.firebaseio.com',
    storageBucket: 'push-notification-b9a18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpUoxm9W_zJuG-GZaGrFz1oPJYEoYBMjg',
    appId: '1:732608529588:ios:3d2f057b34a9781b6a43e1',
    messagingSenderId: '732608529588',
    projectId: 'push-notification-b9a18',
    databaseURL: 'https://push-notification-b9a18-default-rtdb.firebaseio.com',
    storageBucket: 'push-notification-b9a18.appspot.com',
    iosClientId: '732608529588-laaqtft8ib59l9ag2ctv31rllef16uut.apps.googleusercontent.com',
    iosBundleId: 'com.example.nowUiFlutter',
  );
}
